language: python
python:
  - "3.6.8"
env:
  - DJANGO=3.2 DB=postgresql

 # command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

 # command to run tests
script:
  - coverage run manage.py test

after_success:
  - coveralls