# Generated by Django 3.2.4 on 2021-06-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_purchasehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='date',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='address',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='state',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.customer'),
        ),
        migrations.AlterModelTable(
            name='purchasehistory',
            table='ecommerce_purchasehistory',
        ),
    ]
