# Generated by Django 3.2 on 2021-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20210430_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cell_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='cellphone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
