# Generated by Django 3.2.4 on 2021-06-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20210606_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='state',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='zipcode',
        ),
    ]
