# Generated by Django 3.2.4 on 2021-06-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20210607_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='user',
        ),
    ]
