# Generated by Django 3.2 on 2021-05-10 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_customeractivity_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
