# Generated by Django 3.2 on 2021-05-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeractivity',
            options={'verbose_name_plural': 'Customer activities'},
        ),
    ]
