# Generated by Django 3.2 on 2021-06-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_purchasehistory'),
        ('ecommerce', '0017_auto_20210524_0752'),
    ]

    operations = [
    ]
